### PR TITLE
Introduce MempoolInfo

### PR DESCRIPTION
**Pull request by sectore**
Screenshot from 2023-05-11 20-15-26

- [x] `MempoolInfo`
- [x] Misc. icons
- [x] (Quick) re-design of mempool info
- [x] Update `i18n`. Note: ~~`zn` + `hi` needs to be updated by anyone else with more knowledge.~~ ~~`hi` has been disabled temporary (need to be translated before re-enabling)~~

Note: As long as `<For>` has `<Show>` as its parent, it needs to be wrapped in a `<div>` to avoid errors such as not
having a parent element. (see 3928c49)

### CODE REVIEW

**Comment by cryptobeijing** [comment]
T::HomeTitle => "預期的銘文",
    T::ForkGH => "在GitHub上派生",
    T::Audio => "音频",
    T::Audios => "音频集",
    T::Video => "视频",
    T::Videos => "视频集",
    T::Image => "图片",
    T::Images => "图片集",
    T::Pdf => "PDF",
    T::Pdfs => "PDF集",
    T::Unknown => "未知",
    T::Unknowns => "未知集",
    T::Text => "文字",
    T::Texts => "文字集",
    T::Iframe => "框架",
    T::Iframes => "框架集",

**Comment by FelixWeis** [comment]
Thanks for your contribution @cryptobeijing !  中文 is moving forward. can we do both 繁體 (traditional) and 简体 (simplified)?

**Comment by cryptobeijing** [comment]
Simplified Chinese Version
T::HomeTitle => "预期的铭文",
T::ForkGH => "在GitHub上派生",
T::Audio => "音频",
T::Audios => "音频集",
T::Video => "视频",
T::Videos => "视频集",
T::Image => "图片",
T::Images => "图片集",
T::Pdf => "PDF",
T::Pdfs => "PDF集",
T::Unknown => "未知",
T::Unknowns => "未知集",
T::Text => "文字",
T::Texts => "文字集",
T::Iframe => "框架",
T::Iframes => "框架集",

**Comment by cryptobeijing** [comment]
Traditional Chinese Version
T::HomeTitle => "預期的銘文",
T::ForkGH => "在GitHub上派生",
T::Audio => "音頻",
T::Audios => "音頻集",
T::Video => "視頻",
T::Videos => "視頻集",
T::Image => "圖片",
T::Images => "圖片集",
T::Pdf => "PDF",
T::Pdfs => "PDF集",
T::Unknown => "未知",
T::Unknowns => "未知集",
T::Text => "文字",
T::Texts => "文字集",
T::Iframe => "框架",
T::Iframes => "框架集",

**Comment by FelixWeis** [comment]
thanks 1440000bytes, floppy disk guy for reviewing Hindi

**Review by cryptobeijing — COMMENTED** [review]
Chinese (Simplified/ Traditional )Translation Reviewed

**Pull request merged**
